"use strict";
console.log('"hello " worls');
let fullName, firstName, lastName, mail;
mail = "hello@happy.mail.com";
firstName = "Leaon";
lastName = "Geopard";
fullName = firstName + " " + lastName;
console.log(fullName);
console.log("pozycja 3 ", fullName[2]);
console.log(fullName.length);
console.log(fullName.toUpperCase());
console.log(fullName[0].toLowerCase());
let lowerCasedName = fullName.toLowerCase();
console.log(lowerCasedName);
let index = mail.indexOf(".");
console.log(index);
